apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
  labels:
    app: nodejs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
        - name: nodejs-app
          image: enrichosamb/node-js:latest  # <- pastikan image ini sudah ada di Docker Hub atau ganti sesuai registry kamu
          imagePullPolicy: Always
          env:
            - name: DOCKER_DEFAULT_PLATFORM
              value: linux/amd64
          ports:
            - containerPort: 3000
