apiVersion: v1
kind: Service
metadata:
  name: nodejs-app-service
  labels:
    app: nodejs-app
spec:
  selector:
    app: nodejs-app
  ports:
    - port: 5050
      targetPort: 3500
  type: ClusterIP
